### ISSUE TITLE
Libopenblas not found

### ISSUE THREAD

**Issue by jgiret** [conda-forge/pytrilinos-feedstock#15]
Issue: 

While trying to import the Epetra package, I get the following error.

`python -c 'from PyTrilinos import Epetra'`

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/jc.giret/.conda/envs/trilinos/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 73, in <module>
>     _Epetra = swig_import_helper()
>   File "/home/jc.giret/.conda/envs/trilinos/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 72, in swig_import_helper
>     return importlib.import_module('_Epetra')
>   File "/home/jc.giret/.conda/envs/trilinos/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

Then, I install manually openblas by typing the following command under the right conda env:

`conda install -c conda-forge openblas`

When I try again the same python command as before:

` python -c 'from PyTrilinos import Epetra'`

I get the following error:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/jc.giret/.conda/envs/trilinos/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 73, in <module>
>     _Epetra = swig_import_helper()
>   File "/home/jc.giret/.conda/envs/trilinos/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 70, in swig_import_helper
>     return importlib.import_module(mname)
>   File "/home/jc.giret/.conda/envs/trilinos/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ValueError: mpi4py.MPI.Message has the wrong size, try recompiling. Expected 40, got 32

This is strange as both MPICH and MPI4Py have been installed by conda.

<br/>
Environment (<code>conda list</code>):
<details>
blas                      1.0                         mkl    anaconda

ca-certificates           2019.1.23                     0    anaconda

certifi                   2019.3.9                 py27_0    anaconda

intel-openmp              2019.3                      199    anaconda

libedit                   3.1.20181209         hc058e9b_0    anaconda

libffi                    3.2.1                h4deb6c0_3    anaconda

libgcc-ng                 8.2.0                hdf63c60_1    anaconda

libgfortran               3.0.0                         1    anaconda

libgfortran-ng            7.3.0                hdf63c60_0    anaconda

libstdcxx-ng              8.2.0                hdf63c60_1    anaconda

mkl                       2019.3                      199    anaconda

mkl_fft                   1.0.10           py27ha843d7b_0    anaconda

mkl_random                1.0.2            py27hd81dba3_0    anaconda

mpi                       1.0                       mpich    anaconda

mpi4py                    2.0.0                    py27_2    anaconda

mpich                     3.2.1                hf39692e_8    anaconda

mpich2                    1.4.1p1                       0    anaconda

ncurses                   6.1                  he6710b0_1    anaconda

numpy                     1.16.2           py27h7e9f1db_0    anaconda

numpy-base                1.16.2           py27hde5b4d6_0    anaconda

openssl                   1.1.1                h7b6447c_0    anaconda

pip                       19.0.3                   py27_0    anaconda

python                    2.7.16               h9bab390_0    anaconda

pytrilinos                12.10.1          py27h7127e17_2    conda-forge

readline                  7.0                  h7b6447c_5    anaconda

setuptools                41.0.0                   py27_0    anaconda

sqlite                    3.27.2               h7b6447c_0    anaconda

tk                        8.6.8                hbc83047_0    anaconda

wheel                     0.33.1                   py27_0    anaconda

zlib                      1.2.11               h7b6447c_3    anaconda
</details>
<br/>

Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

 active environment : trilinos
    active env location : /home/jc.giret/.conda/envs/trilinos
            shell level : 2
       user config file : /home/jc.giret/.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.9
         python version : 2.7.15.final.0
       base environment : /opt/anaconda/envs/python27_2  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/anaconda/envs/python27_2/pkgs
                          /home/jc.giret/.conda/pkgs
       envs directories : /home/jc.giret/.conda/envs
                          /opt/anaconda/envs/python27_2/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.14.2 CPython/2.7.15 Linux/2.6.32-696.3.1.el6.x86_64 centos/6.9 glibc/2.12
                UID:GID : 20719:10513
             netrc file : None
           offline mode : False

</details>

**Comment by jgiret** [comment]
Hello,

I think I have found the issue, I created my environment using the following environment:

```
name: trilinos
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=2.7
  - pytrilinos
```

Setting conda-forge as top-priority channel solves the issue:

```
name: trilinos
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=2.7
  - pytrilinos
```

I close the ticket.
